name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install server dependencies
      run: npm install
      working-directory: ./server
    - name: Run tests
      run: npm test
      working-directory: ./server

  test_client:
    runs-on: ubuntu-latest
    needs: test_server
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install client dependencies
      run: npm install
      working-directory: ./client
    - name: Run tests
      run: npm test
      working-directory: ./client
